# Generated by Django 5.1.6 on 2025-02-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameanalytics',
            name='size',
            field=models.TextField(blank=True, help_text="Enter game size (e.g., '500 MB' or '2.5 GB')"),
        ),
    ]
